<section>
    
    <div class="homepage">
        <div class="opacity">
            <h2>C.S.L.</h2>
            <h2>Chauffage & Sanitaire</h2>
           
            <a href="#presentations"> <i class="fa-solid fa-angle-down fleche-bas"></i></a>
        </div>
    </div>
    
    
    <div id="presentations" class="presentations">
        
        <div class="presentation">
            <div><img src="./public/img/homepage/icons/batiment.png"></div>
            <div><h3>Compétences</h3>
                <p>J'effectue tout type de travaux à domicle : plomberie, chauffage, gaz.</p>
                <p>Je me charge également de la maintenance de vos installations sanitaire et de chaudieres pour un suivi 100% personaliser !</p>
                <p>Dépannage ou remplacement de materiel, je m'occupe de tout !</p>
                
        
            </div>
            
            
        </div>
        <div class="presentation">
            <div>
                <img src="./public/img/homepage/icons/boite-a-outils.png">
            </div>
            <div>
                <h3>Savoir-faire</h3>
                <p>Depuis le debut de mon activité, je met toutes mes compétences au service de mes clients.</p>
                <p>Dans le respect des normes francaises, je vous conseil les meilleurs équipements afin de convenir au mieux à chacun de mes clients. </p>
            </div>
        </div>
        <div class="presentation">
            <div>
                <img src="./public/img/homepage/icons/les-mieux-notes.png">
            </div>
            <div>
                <h3>Expertise</h3>
                <p>Depuis plus de 20ans, j'ai pu créer une relation de confiance avec mes clients.</p>
                <p>Mes compétences me permette chaque jours de faire de nouvelles rencontres grace aux nombreuses recommendations.</p>
                <p>Convivialité et professionalisme, sont au coeur de mon travail.</p>
            </div>   
        </div>
        
        
        
    </div>
    
    <div class="imgback">
       
    </div>
    
    <div class="metiers">
        <div class="metier">
            <img src="./public/img/homepage/icons/soupape.png">
            <h3>Plomberie</h3>
            <a href='index.php?route=plomberie' class="btn" > + d'infos !</a>
        </div>
        <div class="metier">
            <img src="./public/img/homepage/icons/flamme.png">
            <h3>Chauffage</h3>
            <a href='index.php?route=chauffage' class="btn"> + d'infos !</a>
        </div>
        <div class="metier">
            <img src="./public/img/homepage/icons/gaz-naturel.png">
            <h3>Gaz</h3>
            <a href='index.php?route=gaz' class="btn"> + d'infos !</a>
        </div>
    </div>



    <article>
        <h2>Quelques une de mes réalisation</h2>
    </article>


    <article>
        <h2>Mes qualifications :  </h2>
    </article>
    
</section>