<section class="sections">
<div class="startPage chauffage">
        <h2>Chauffage</h2>
    </div>

    <article class="Article Article1">
        <div>
            <picture>
                <source  media="(max-width: 768px)" srcset="./public\img\homepage\radiator-gb09c5a6d1_640.jpg">
                <source media="(min-width: 768px) " srcset="./public\img\homepage\radiator-g84fd5f665_1280.jpg">
                <source media="(min-width: 1024px)" srcset="./public\img\homepage\radiator-g1ea49f64a_1920.jpg">
                <img class="imgSite img1" src="./public\img\homepage\radiator-gb09c5a6d1_640.jpg" alt="robinet">
                    
            </picture>
        </div>
        <div>
            <h3 class="title-page">Chauffage</h3>
            <p>Le chauffage est un des points les plus primordiaux pour traverser les longs mois d'hiver. De ce fait, une installation adéquate est essentielle ! Nous nous chargeons de toute votre installation (neuve ou rénovation) de votre système de chauffage !</p>
        </div>
    </article>

    <div class="trait"></div>

    <article class="Article Article2">
        <div>
            <picture>
                
                <img class="imgSite img2" src="./public\img\homepage\pexels-cottonbro-4786270.jpg" alt="salle d'eau">
                    
            </picture>
        </div>
        <div>
            <h3 class="title-page">Se chauffer, un goufre financier ?</h3>
            <p>Les évolutions technologiques nous permettent de mieux se chauffer et d'en réduire les pertes également. À travers un diagnostic complet de votre habitat, et de vos équipements, nous vous conseillerons les meilleures solutions pour vous garantir les meilleures optimisations rapport coût/chauffage .</p>
        </div>
    </article>
    

    <div class="trait"></div>

    <a href='index.php?route=contact' class="btn btn-devis"> Demandez votre devis gratuitement !</a>
</section>