<section class="sections">
    <div class="startPage gaz">
        <h2>Gaz</h2>
    </div>

    <article class="Article">
        <div>
            <picture>
                <source  media="(max-width: 768px)" srcset="./public\img\homepage\flame-g4c702c2e4_640.jpg">
                <source media="(min-width: 768px) " srcset="./public\img\homepage\flame-gff37d5d03_1280.jpg">
                <source media="(min-width: 1024px)" srcset="./public\img\homepage\flame-gff37d5d03_1280.jpg">
                <img class="imgSite" src="./public\img\homepage\flame-g4c702c2e4_640.jpg" alt="flamme">
                    
            </picture>
        </div>

        
        <div>
            <h3 class="title-page">Professionel du gaz</h3>
            <p>L'installation du gaz exige certaines compétences essentielles pour assurer une sécurité optimale pour nos clients.</p>
            <p>Nous sommes agréé pour l'installation de gaz de ville, pour votre chaudières (chauffage et eau chaude) et appareil ménager utilisant du gaz.</p>
        </div>
    </article>

    
    <div class="trait"></div>


    <a href='index.php?route=contact' class="btn btn-devis"> Demandez votre devis gratuitement !</a>
</section>