<section class="sections">
    <div class="startPage plomberie">
        <h2>Plomberie</h2>
    </div>

    

        <article class="Article Article1">
            <div>
                <picture>
                    <source  media="(max-width: 768px)" srcset="./public\img\homepage\water-tap-g76c6e00fd_640.jpg">
                    <source media="(min-width: 768px) " srcset="./public\img\homepage\water-tap-g40c9829e6_1280.jpg">
                    <source media="(min-width: 1024px)" srcset="./public\img\homepage\water-tap-gce7951478_1920.jpg">
                    <img class="imgSite" src="./public\img\homepage\water-tap-g76c6e00fd_640.jpg" alt="robinet">
                        
                </picture> 
            </div>
            <div>
                <h3 class="title-page">Plomberie</h3>
                <p>Chez C.S.L Chauffage sanitaire longipontain, nous nous occupons de tous types de travaux de plomberies, travaux d'évacuation d'eaux usées, alimentation d'eau chaude et eau froide, les appareillages sanitaires, robinets, soupapes, pompes aux différents points d'usage de  votre installation. Nous respectons les normes francaises, nous vous garantissons un travail de qualité depuis plus de 20 ans !</p>
            </div>
        </article>

        <div class="trait"></div>

        <article class="Article Article2">
            <div>
                <picture>
                    
                    <img class="imgSite img2" src="./public\img\homepage\pexels-vecislavas-popa-3741317.jpg" alt="salle d'eau">
                        
                </picture>
            </div>
            <div>
                <h3 class="title-page">Sanitaires</h3>
                <p>La qualité est primordiale pour nous, nous mettons tout en oeuvre pour satisfaires la moindre de vos exigences.</p>
                <p>Esthétiques, qualité des matériaux et précisions sont ce qui nous représente le plus.</p>
            </div>
        </article>
        

        <div class="trait"></div>

        <a href='index.php?route=contact' class="btn btn-devis"> Demandez votre devis gratuitement !</a>
    
</section>