<section class="sectionsource">

<table>
   
    <tbody>
        
        <tr>
            <td><img class="icones" src="./public/img/homepage/icons/batiment.png"></td>
            <td><a href="https://www.flaticon.com/fr/icones-gratuites/empire-state-building" title="empire-state-building icônes" target="_blank">Empire-state-building icônes créées par surang - Flaticon</a></td>
            
        </tr>

        <tr>
            <td><img class="icones" src="./public/img/homepage/icons/boite-a-outils.png"></td>
            <td><a href="https://www.flaticon.com/fr/icones-gratuites/outils" title="outils icônes" target="_blank">Outils icônes créées par Freepik - Flaticon</a></td>
            
        </tr>

        <tr>
            <td><img class="icones" src="./public/img/homepage/icons/les-mieux-notes.png"></td>
            <td><a href="https://www.flaticon.com/fr/icones-gratuites/les-mieux-notes" title="les-mieux-notes icônes" target="_blank">Les-mieux-notes icônes créées par Freepik - Flaticon</a></td>
        </tr>


        <tr>
            <td><img class="icones" src="./public/img/homepage/icons/soupape.png"></td>
            <td><a href="https://www.flaticon.com/fr/icones-gratuites/tuyau" title="tuyau icônes" target="_blank">Tuyau icônes créées par smalllikeart - Flaticon</a></td>
        </tr>

        <tr>
            <td><img class="icones" src="./public/img/homepage/icons/flamme.png"></td>
            <td><a href="https://www.flaticon.com/fr/icones-gratuites/gaz-naturel" title="gaz naturel icônes" target="_blank">Gaz naturel icônes créées par Freepik - Flaticon</a></td>
        </tr>

        <tr>
            <td><img class="icones" src="./public/img/homepage/icons/gaz-naturel.png"></td>
            <td><a href="https://www.flaticon.com/fr/icones-gratuites/gaz" title="gaz icônes" target="_blank">Gaz icônes créées par surang - Flaticon</a></td>
        </tr>
    </tbody>
</table>
</section>